### PR TITLE
Ferroelectric workflow (3rd time's the charm!)

### PR DESCRIPTION
**Pull request by blondegeek**
WARNING: Tests for get_wf_ferroelectric are included but are not passing. None of the other workflow tests seem to be currently passing either so I assume something nontrivial changed. **Please advise on what changes should be made.**

This pull requests adds the following classes and functions for the workflow for calculating the polarization of candidate ferroelectrics:
atomate.vasp.workflows.base.ferroelectric.get_wf_ferroelectric
atomate.vasp.fireworks.core.LcalcpolFW
atomate.vasp.fireworks.core.StaticInterpolateFW
(Some comments are included with suggestions for improving this FW)
atomate.vasp.firetasks.glue_tasks.GetInterpolatedPOSCAR
atomate.common.firetasks.glue_tasks.CreateFolder
atomate.common.firetasks.glue_tasks.GrabFilesFromCalcLoc
atomate.vasp.firetasks.parse_outputs.PolarizationToDbTask

### CODE REVIEW

**Comment by computron** [comment]
Hi @blondegeek

All the tests should pass. Actually this is auto-checked after every commit via CircleCI which shows the state of every build.

Most likely you need to update your atomate dependencies (pymatgen, etc) via a fresh "python setup.py develop" or similar command

**Comment by blondegeek** [comment]
Hi @computron 

I updated all my dependencies (which did fix several of the errors I was getting) and even tried making a fresh virtual environment. However, out of all the tests in atomate/vasp/workflows/tests directory I can only get test_vasp_workflows.py to pass. The errors are each very different (I can provide more detail if helpful).

I am also getting some very strange errors from the test_ferroelectric_workflow.py unit tests which were previously passing back when I made the first ferroelectric workflow pull request.

For example, line 165 in test_ferroelectric_workflow.py will throw an error because the workflow fireworks are empty (and do not have a "_task" keyword) unless I have a `print(cls.wf.fws)` or `print(self.wf.fws)` (depending on where you put it) somewhere (for example, around line 56) before that line runs. *facepalm at print statement sensitive executions*

```
Traceback (most recent call last):
  File "test_ferroelectric_workflow.py", line 166, in test_wf
    for fw in self.wf.fws if "polarization" in fw.name and "interpolation" in fw.name]
KeyError: u'_tasks'
```

Also, when I do have the print statement included, the tests run but then there's a failure due to a mismatch of KPOINT files. 

```
ValueError: KPOINT files are inconsistent! Paths are:
/Users/tesssmidt/Dropbox/code_ferroelectric_commit/env/src/atomate/atomate/vasp/workflows/tests/scratch/launcher_2017-06-06-06-46-12-291067
/Users/tesssmidt/Dropbox/code_ferroelectric_commit/env/src/atomate/atomate/vasp/test_files/ferroelectric_wf/interpolation_1_polarization/inputs with kpoints Automatic kpoint scheme
0
Gamma
7 7 6
 and Automatic kpoint scheme
0
Monkhorst
8 8 8
```

There's nothing inherently wrong with this error, especially since it seems the pymatgen 4.7.6 has different kpoint sampling defaults. However, if (with DEBUG=True in the previous step) I do the following:

```
rm .../atomate/atomate/vasp/test_files/ferroelectric_wf/interpolation_1_polarization/inputs/KPOINTS
mv .../atomate/atomate/vasp/workflows/tests/scratch/launcher_2017-06-06-06-40-41-501031/polarization/KPOINTS .../atomate/atomate/vasp/test_files/ferroelectric_wf/interpolation_1_polarization/inputs/.
```

I get the following error:

```
ValueError: KPOINT files are inconsistent! Paths are:
.../atomate/atomate/vasp/workflows/tests/scratch/launcher_2017-06-06-06-40-41-501031/polarization
.../atomate/atomate/vasp/test_files/ferroelectric_wf/interpolation_1_polarization/inputs with kpoints Automatic kpoint scheme
0
Monkhorst
8 8 8
 and Automatic kpoint scheme
0
Gamma
7 7 6
```

The KPOINTS files have swapped! Grrrr.....

At this point, I am tempted to throw my computer across the room to see if that will help in the debugging process. I would very much like to finalize this pull request in a timely manner, but I am baffled as to what is going on!

Can you reproduce these errors?

Tess

**Comment by bocklund** [comment]
Github is saying that your glue_tasks conflicts with the hackingmaterials:master branch. And your ferroelectric_2 is reporting 2 commits head, 36 behind hackingmaterials:master.  Maybe you are developing in the middle of some broken state?

Do the tests pass if you just run them on the hackingmaterials:master branch?

**Comment by bocklund** [comment]
Also with regards to print statement dependency, I think I was experiencing something similar in the Gibbs tests that I wrote in #75. I tried more after that, but never got to the bottom of it.

My test was, relatively speaking, longer running (about a minute). My best guess is that nose (which is what I use, but in pure Python I had the same issues) runs setup/teardown in parallel. Meaning files and the database, could be getting cleaned out while other tests are still running and using them. I wasn't able to find clear documentation on this and I never got around to actually reading the source code for test runners to confirm. But it seemed consistent. 

The fact that just a print statement is causing your success or failure has me questioning that conclusion, but hopefully we can figure it out and solve both problems.

Perhaps mocking the database would be better than actually accessing it. That seems to be better practice around web-dev people and would isolate each test in its own sandbox properly.

**Comment by computron** [comment]
@blondegeek you might try a fresh install? @bocklund seems to have gotten it to work out OK that way - minus the ferroelectric test which looks like a legitimate bug

**Comment by computron** [comment]
@blondegeek do you want to schedule a call to try to sort this out?

**Comment by blondegeek** [comment]
I'll follow up via email.

**Comment by computron** [comment]
Hi @blondegeek I am closing this pull request since based on last conversation it is not ready. Please re-open when ready

**Pull request closed without merging**
