### PR TITLE
Config script

### PR DESCRIPTION
**Pull request by shyamd**
A simple config script for atomate. 
 * some basic defaults for most values
 * can boot-strap my_launchpad.yaml, my_fworker.yaml, and my_qadapter.yaml from existing files

### CODE REVIEW

**Comment by bocklund** [comment]
As another side comment, @computron has suggested (and the documentation reflects) using rapidfire instead of singleshot in the queueadapters. We should provide the option for users to use a reservation + singleshot approach, but IMO the default should be consistent with our docs to launch with rapidfire within the walltime.

**Comment by shyuep** [comment]
I suggest looking at pymatgen-db's `mgdb init` as an example.

**Comment by shyamd** [comment]
@bocklund I agree. I've coded this up for the use cases I've experienced in on-boarding undergrads to using atomate and put the pull request up to get feedback. I think a fully interactive mode would be a good idea, but shouldn't take away from a simple noninteractive mode. Let me add that in today.

**Comment by shyamd** [comment]
temp closing to clean up the pull request

**Pull request closed without merging**
