### PR TITLE
Gibbs: phonon workflow test, results to database, improved defaults

### PR DESCRIPTION
**Pull request by bocklund**
# **Do not merge yet!**

I need some help in the Gibbs phonon unit test. I modeled it similarly to the existing elastic workflow unit test. In isolation, it works well, passes, and tests what I think it should test. But I get several errors when I try to test the whole atomate test suite. 

I've done a git bisect and determined that the whole test suite works up until commit 83b525d, where I add in the phonon workflow test. None of the errors are in the phonon workflow, but are elsewhere. See the comments below for more details on these. 

Once this is fixed, we can merge.

## Summary

A unit test was written for the Gibbs workflow with Phonopy. Debye mode files are included, workflow unit test coming soon. 

The results from the Gibbs workflows (information about the structure, the free energies, temperatures, and meta data) are written to a "gibbs" collection. (With this, a rename of GibbsFreeEnergyTask to GibbsFree

The following defaults for the Gibbs workflows were changed or updated

* `natoms` in `gibbs_summary_dict` changed to `nsites` to better conform with the style elsewhere
* Gibbs deformations changes
  - Default number of deformations to 11, which should be plenty for an average user of the Debye method and the most anyone using Phonopy should need. See http://dx.doi.org/10.1016/j.commatsci.2009.12.006 for more
  - The deformation matrix was changed so that the value passed from `np.linspace` represents the actual volume change. E.g. `np.linspace(-0.10, 0.10, 11)` makes 11 deformations from -10% volume to +10% volume.
* Fix phonopy `t_max` by adding several steps to the maximum temperature given to `PhonopyQHA` because it truncates several values in the fitting. Now the final `t_max` matches the input from the user.
* Use higher accuracy force INCAR settings by default (`LREAL=False`, `ADDGRID=True`)

More details for several of these can be found in the commits. 

## TODO (if any)

* Write a workflow unit test for the "debye_model" mode for the Gibbs free energy preset.

@matk86 should take a look at the changes in the Gibbs preset.

### CODE REVIEW

**Comment by bocklund** [comment]
Errors that the phonon test (83b525d) introduced:

```
======================================================================
ERROR: test_ioset_explicit (atomate.vasp.tests.test_write_vasp.TestWriteVasp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 70, in as_dict
    args = list(inspect.signature(self.__init__).keys())
AttributeError: 'Signature' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/tests/test_write_vasp.py", line 83, in test_ioset_explicit
    ft = load_object(ft.to_dict())  # simulate database insertion
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 175, in _decorator
    m_dict = func(self, *args, **kwargs)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 149, in _decorator
    m_dict = recursive_dict(m_dict)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 90, in recursive_dict
    for k, v in obj.items()}
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 90, in <dictcomp>
    for k, v in obj.items()}
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 83, in recursive_dict
    return recursive_dict(obj.as_dict(), preserve_unicode)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 72, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

```

The second half (the monty deprecation warning) happens several times such as in these

```
======================================================================
ERROR: test suite for <class 'test_raman_workflow.TestRamanWorkflow'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 70, in as_dict
    args = list(inspect.signature(self.__init__).keys())
AttributeError: 'Signature' object has no attribute 'keys'
```

```
======================================================================
ERROR: test suite for <class 'atomate.vasp.tests.test_vasp_powerups.TestVaspPowerups'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 70, in as_dict
    args = list(inspect.signature(self.__init__).keys())
AttributeError: 'Signature' object has no attribute 'keys'
```

```
======================================================================
ERROR: test_bandgap_check_Vasp (atomate.vasp.tests.test_vasp_workflows.TestVaspWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/tests/test_vasp_workflows.py", line 253, in test_bandgap_check_Vasp
    "db_file": ">>db_file<<"})
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/base/core.py", line 51, in get_wf
    d["fireworks"][0]["params"]["vasp_input_set"] = vis.as_dict()
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 72, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

```
======================================================================
ERROR: test_bandstructure_Vasp (atomate.vasp.tests.test_vasp_workflows.TestVaspWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/tests/test_vasp_workflows.py", line 215, in test_bandstructure_Vasp
    "db_file": ">>db_file<<"})
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/base/core.py", line 51, in get_wf
    d["fireworks"][0]["params"]["vasp_input_set"] = vis.as_dict()
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 72, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

```
======================================================================
ERROR: test_single_Vasp (atomate.vasp.tests.test_vasp_workflows.TestVaspWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/tests/test_vasp_workflows.py", line 172, in test_single_Vasp
    common_params={"vasp_cmd": VASP_CMD})
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/base/core.py", line 51, in get_wf
    d["fireworks"][0]["params"]["vasp_input_set"] = vis.as_dict()
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 72, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

```
======================================================================
ERROR: test_trackers (atomate.vasp.tests.test_vasp_workflows.TestVaspWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/tests/test_vasp_workflows.py", line 281, in test_trackers
    common_params={"vasp_cmd": VASP_CMD})
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/base/core.py", line 51, in get_wf
    d["fireworks"][0]["params"]["vasp_input_set"] = vis.as_dict()
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/monty/json.py", line 72, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

**Comment by bocklund** [comment]
I'm not sure why adding the `test_gibb_workflow.py` file could have affected these tests, unless it is doing something funny with the database. I don't see how that could be though, considering I use the same method for interacting with the database as in `test_elastic_workflow.py`.

**Comment by bocklund** [comment]
I just verified that with the both the `test_gibb_workflow.py` and the tests above work in isolation (testing each file separately), but not together. Any insight would be appreciated.

**Comment by matk86** [comment]
couple of things:

1. I want to retain the option of writing to json file option for debugging purposes.

2. i set the default to 21, because thats what i used to benchmark the workflow against mpworks implementation on about 69 structures(the implementation in mpworks uses atleast 21 datapoints). I know its an overkill but i would like to leave it like that.
. 
3. The only difference between gibbs workflow and elastic workflow is the final analysis firework(this can scraped too since the analysis part is pretty trivial once all the data is available). Since elastic workflow already has the tests for the structure deformation part, in my opinion the only test needed is the test for final analysis part which i recently added for the quasi harmonic approx.

**Comment by matk86** [comment]
are you working with the same verison of monty as mentioned in requirements.txt file?

**Comment by bocklund** [comment]
The above issues were with monty 0.9.6. 

You make a good point regarding the test, but I would like to test that everything is being parsed correctly and be able to get flagged if changes are made to the default configuration that makes the results non-sensible (e.g. the default `t_max` returned was previously not the `t_max` set by the user. A test confirms that this doesn't revert). Could it be possible just to test that FireWork rather than the whole workflow? If not, I think it's reasonable to leave this in. Like you did for the Debye model, the Phonopy results should be tested separately, but I still think there is value in making sure that the inputs give the correct quantities of outputs. 

I'll add in an option to write the file in the config dict, but I think the default should be off (`c["write_gibbs_file"]=False`). If you would rather it be `True`, that is fine, but for a default it is mostly wasted space on the drive, IMO. 

I still feel that the default should be what a typical user would need if they were to use the preset workflow. So ~11 for Debye (and possibly less for phonons). I think benchmarking against the MP is a special case. Otherwise every user will have to construct their own deformations to get efficient, useful calculations because there are only 69 structures in the MP.

**Comment by matk86** [comment]
adding tests for gibbs wflow using phonopy is useful, rest leave it as it is...

**Comment by bocklund** [comment]
Still working on trying to isolate the part of the Gibbs wf test that is making the other tests fail. By 

> rest leave it as it is...

Do you mean leave it as I have changed it here (in bocklund/master) or leave it as it is in atomate/master?

**Comment by matk86** [comment]
in the atomate/master... i would suggest you make a new pull request, also if possible run your tests first locally in both 2.7 and 3.5 environments.. if the problem persists, let me know, i will take a look at it..
closing this pr for now..

**Comment by bocklund** [comment]
The errors seem to be related to using nose. Using the builtin `unittest` module worked fine, though I did add a `__init__.py` to the `workflows/test` directory. I updated the initial PR comment to reflect that this can be merged when we resolve any changes that I need to make.

**Comment by bocklund** [comment]
So you do not want to merge the `GibbsFreeEnergyToDbTask`? I think writing results to a database fits the pattern laid out by the other preset workflows, such as the elastic and raman. Creating database entries is how we are using the workflow it in my group. I see no point in rewriting a test to conform to current code (writing files) when there are clear and justifiable improvements in this PR.

**Comment by matk86** [comment]
sure, like i said before: retain json dump option and make a new pull request(that takes into account my suggestions) after running your tests locally in 2.7 and 3.5

**Comment by bocklund** [comment]
Great. I still need some help on getting the tests to work, if you wouldn't mind helping.

Starting from the project root dir and run `python -m unittest` (note that I had to make an `__init__.py` in the vasp/workflows/tests directory to make unittest discover them) I get 

```
======================================================================
ERROR: setUpClass (atomate.vasp.workflows.tests.test_raman_workflow.TestRamanWorkflow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandon/Projects/monty/monty/json.py", line 71, in as_dict
    args = list(inspect.signature(self.__init__).keys())
AttributeError: 'Signature' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/tests/test_raman_workflow.py", line 46, in setUpClass
    cls.wf = wf_raman_spectra(cls.struct_si, cls.raman_config)
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/presets/core.py", line 227, in wf_raman_spectra
    vasp_cmd=c.get("vasp_cmd", "vasp"), db_file=c.get("db_file", None))
  File "/Users/brandon/Projects/atomate/atomate/vasp/workflows/base/raman.py", line 54, in get_wf_raman_spectra
    db_file=db_file)
  File "/Users/brandon/Projects/atomate/atomate/vasp/fireworks/core.py", line 55, in __init__
    format(structure.composition.reduced_formula, name), **kwargs)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/core/firework.py", line 206, in __init__
    self.spec['_tasks'] = [t.to_dict() for t in tasks]
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/core/firework.py", line 206, in <listcomp>
    self.spec['_tasks'] = [t.to_dict() for t in tasks]
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 175, in _decorator
    m_dict = func(self, *args, **kwargs)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 149, in _decorator
    m_dict = recursive_dict(m_dict)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 90, in recursive_dict
    for k, v in obj.items()}
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 90, in <dictcomp>
    for k, v in obj.items()}
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/fireworks/utilities/fw_serializers.py", line 83, in recursive_dict
    return recursive_dict(obj.as_dict(), preserve_unicode)
  File "/Users/brandon/.virtualenvs/atomate35/lib/python3.5/site-packages/pymatgen/io/vasp/sets.py", line 165, in as_dict
    d = MSONable.as_dict(self)
  File "/Users/brandon/Projects/monty/monty/json.py", line 73, in as_dict
    args = inspect.getargspec(self.__init__).args
  File "/Users/brandon/.pyenv/versions/3.5.3/lib/python3.5/inspect.py", line 1040, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

----------------------------------------------------------------------
Ran 55 tests in 157.600s
```

Running `python -m unittest atomate/vasp/workflows/tests/test_gibbs_workflow.py` passes and so does running `python -m unittest atomate/vasp/workflows/tests/test_raman_workflow.py`

This is from my commit 83b525d. If I go back one commit to db8d895 and run `python -m unittest` then everything works fine. The only difference between those two commits is my `test_gibbs_workflow.py` file.

This was with python3.5.3, FireWorks 1.4.1, monty 0.9.6, pymatgen 4.6.1

**Comment by matk86** [comment]
ok, send me the link to your development branch(the one that you are trying to merge)

**Comment by bocklund** [comment]
It's https://github.com/bocklund/atomate and my master branch.

**Comment by matk86** [comment]
i ran nosetests on the vasp folder in your fork in both 2.7.12 and 3.5.2(on ubuntu)...in both cases there is only one error and its coming from your test module(test_gibbs_workflow.TestGibbsWorkflowPhonon), it had nothing to do with the monty package...maybe you should try the tests in a fresh virtual environment...

**Comment by bocklund** [comment]
I just installed fresh in a new environment on my Xubuntu machine at home. Still saw the same issues. Did you make a new environment when you tested my fork? If so, did you remember to install phonopy?

**Comment by matk86** [comment]
yes, new enviroments but without phonopy..

**Comment by matk86** [comment]
with phonopy all the tests passed in 2.7

**Comment by matk86** [comment]
it fails in 3.5, seems like your test module is leaving some stuff behind in the db causing the tests that follows it to fail(they all pass when run independently)...

**Comment by bocklund** [comment]
I tried looking my local database and I only have the databases `admin` and `local` after running the test and the collections `system.verison` and `startup_log` are the only ones in each of those databases.

I'm not a testing expert, but is it possible that the setup/teardown methods are not run serially and there is a race condition where a collection created by the Gibbs test isn't being deleted before the next tests start setting up?

**Comment by bocklund** [comment]
Or maybe the other way around... The Raman (for example) starts setting up databases, but the gibbs deletes it which is giving the 'Signature' object has no attribute 'keys'

**Comment by bocklund** [comment]
Also I don't see how it can leave stuff hanging around in 3.5 but not 2.7, unless the tests are implemented differently.

**Comment by bocklund** [comment]
I don't think it's related to the database. I changed only my Gibbs test to use an offsite database for for the launchpad and results databases and kept all of the other tests using my localhost database. Still got the same errors.

**Comment by bocklund** [comment]
Going to strip everything out and add the methods of the class in one by one to figure out what the problem is.

**Comment by matk86** [comment]
ok, do the tests in small pieces..

**Comment by bocklund** [comment]
Keeping all the setup the same, if `test_wf` method looks like this:

```
  def test_wf(self):
        self.wf = self._simulate_vasprun(self.wf)
        self.assertEqual(len(self.wf.fws), 7)

        self.lp.add_wf(self.wf)
        return
```

then everything passes. If it looks like:

```
  def test_wf(self):
        self.wf = self._simulate_vasprun(self.wf)
        self.assertEqual(len(self.wf.fws), 7)

        self.lp.add_wf(self.wf)

        rapidfire(self.lp, fworker=FWorker(env={"db_file": os.path.join(tester_dir, "db.json")}))
        return
```

Then things fail. So something with actually running the fireworks is leading to a problem. Note that the `tester_dir` is for my custom database hosted at mlab, so this workflow isn't accessing my local test database that the other tests are using. So I don't think its a database issue. Any thoughts?

**Comment by bocklund** [comment]
Somehow calling out to phonopy seems to be the problem. If I change the following lines in `atomate.tools.analysis` 

in `get_phonopy_gibbs`: (line 290)

```
    # quasi-harmonic approx
    phonopy_qha = get_phonopy_qha(energies, volumes, force_constants, structure, t_min, t_step,
                                  t_max, mesh, eos, pressure=pressure)

    # gibbs free energy and temperature
    #max_t_index = phonopy_qha._qha._max_t_index
    #G = phonopy_qha.get_gibbs_temperature()[:max_t_index]
    #T = phonopy_qha._qha._temperatures[:max_t_index]
    G = np.linspace(0, 1, 151).tolist()
    T = np.linspace(0, 1, 151).tolist()

    return G, T
```

Here I just commented out the calls to `phonopy_qha` because I made that function return `None`:

in `get_phonopy_qha`: (line 359)
```

    # add pressure contribution
    energies = np.array(energies) + np.array(volumes) * pressure / EVAngstromToGPa
    # quasi-harmonic approx

    # PhonopyQHA(volumes, energies, eos=eos, temperatures=temperatures[0],
    #                   free_energy=np.array(free_energy).T, cv=np.array(cv).T,
    #                   entropy=np.array(entropy).T, t_max=np.max(temperatures[0]))
    return
```

I changed the `return PhonopyQHA(...)` to simply call out instead of returning itself and then I return `None`. Leaving that commented out passes, but  uncommenting it causes the tests to fail.

**Pull request closed without merging**
