### PR TITLE
update KSPACING in test per pymatgen #2163 change

### PR DESCRIPTION
**Pull request by rkingsbury**
pymatgen [PR #2163](https://github.com/materialsproject/pymatgen/pull/2163/files) recently made a small modification to the formula that `MPScanRelaxSet` uses to calculate the KSPACING value from the bandgap. This caused 2 problems in the atomate tests that are currently causing the dev and main tests to fail.

First, the expected value of KSPACING needs to be adjusted slightly to reflect the updated formula. I fix that here.

Second, we need to implement a bugfix in pymatgen to ensure that materials with very large bandgaps (~9 eV) do not result in negative KSPACING values, which is what happened here for the 2 LiF-based atomate tests. Pymatgen [PR #2179](https://github.com/materialsproject/pymatgen/pull/2179) will take care of the second fix.

### CODE REVIEW

**Comment by rkingsbury** [comment]
FYI @mkhorton , related to the recent KSPACING formula change

**Comment by rkingsbury** [comment]
Would someone be able to re-run the CI tests here? I don't think I have permissions to do so. The pymatgen fix has been merged so py3devtest should now pass.

**Comment by rkingsbury** [comment]
I can't figure out why the CI test can't find the latest pymatgen release. I know it's less than 24 hr old but I don't remember running in to this problem before. I believe this PR and #653 should pass all tests with pymatgen 2022.0.10.

Please re-run the CI tests when ready, or let me know if I need to take further action to do so. Thanks!

```
ERROR: Could not find a version that satisfies the requirement pymatgen==2022.0.10 (from versions: 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.8, 1.2.9, 1.5.0, 1.6.0, 1.7.0, 1.7.2, 1.8.0, 1.8.2, 1.8.3, 1.9.0, 2.0.0, 2.1.0, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2b0, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.10, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6, 2.9.7, 2.9.8, 2.9.9, 2.9.10, 2.9.11, 2.9.12, 2.9.13, 2.9.14, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.10.6, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.13, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.4.0, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.3.0, 4.3.1, 4.3.2, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 4.4.8, 4.4.9, 4.4.10, 4.4.11, 4.4.12, 4.5.0, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 4.5.5, 4.5.6, 4.5.7, 4.6.0, 4.6.1, 4.6.2, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 2017.6.8, 2017.6.22, 2017.6.24, 2017.7.4, 2017.7.21, 2017.8.4, 2017.8.14, 2017.8.16, 2017.8.20, 2017.8.21, 2017.9.1, 2017.9.3, 2017.9.23, 2017.10.16, 2017.11.6, 2017.11.9, 2017.11.27, 2017.11.30, 2017.12.6, 2017.12.8, 2017.12.15, 2017.12.16, 2017.12.30, 2018.1.19, 2018.1.29, 2018.2.13, 2018.3.2, 2018.3.13, 2018.3.14, 2018.3.23, 2018.4.6, 2018.4.20, 2018.5.3, 2018.5.14, 2018.5.21, 2018.5.22, 2018.6.11, 2018.6.27, 2018.7.15, 2018.7.23, 2018.8.7, 2018.8.10, 2018.9.1, 2018.9.12, 2018.9.19, 2018.9.30, 2018.10.18, 2018.11.6, 2018.11.30, 2018.12.12, 2019.1.13, 2019.1.24, 2019.2.4, 2019.2.24, 2019.2.28, 2019.3.13, 2019.3.27, 2019.4.11, 2019.5.1, 2019.5.8, 2019.5.28, 2019.6.5, 2019.6.20, 2019.7.2, 2019.7.21, 2019.7.30, 2019.8.14, 2019.8.23, 2019.9.7, 2019.9.8, 2019.9.12, 2019.9.16, 2019.10.2, 2019.10.3, 2019.10.4, 2019.10.16, 2019.11.11, 2019.12.3, 2019.12.22, 2020.1.10, 2020.1.28, 2020.3.2, 2020.3.13, 2020.4.2, 2020.4.29, 2020.6.8, 2020.7.3, 2020.7.10, 2020.7.14, 2020.7.16, 2020.7.18, 2020.8.3, 2020.8.13, 2020.9.14, 2020.10.9, 2020.10.9.1, 2020.10.20, 2020.11.11, 2020.12.3, 2020.12.18, 2020.12.31, 2021.2.8, 2021.2.8.1, 2021.2.13, 2021.2.14, 2021.2.16, 2021.3.3, 2021.3.4, 2021.3.5, 2021.3.9, 2022.0.0, 2022.0.1, 2022.0.2, 2022.0.3, 2022.0.4, 2022.0.5, 2022.0.6, 2022.0.7, 2022.0.8, 2022.0.9)
ERROR: No matching distribution found for pymatgen==2022.0.10
```

**Comment by mkhorton** [comment]
That would be because the pymatgen 2022.0.10 release failed

**Comment by mkhorton** [comment]
I've re-triggered it, it should be up within the hour

**Comment by mkhorton** [comment]
Ok this is done now

**Comment by rkingsbury** [comment]
@computron could you please review and merge at your earliest convenience? This PR is necessary in order for atomate tests to pass with the latest pymatgen. We're pushing ahead with our SCAN work and I want to make sure the workflow is fully integrated into our codes. Thanks.

**Comment by mkhorton** [comment]
@Zhuoying or @itsshawnzhang, would it be possible to get this merged?

**Comment by mkhorton** [comment]
Thanks @Zhuoying !

**Comment by Zhuoying** [comment]
Hi @rkingsbury It seems a value assertion error for the unit test of SCAN workflow [here](https://app.circleci.com/pipelines/github/hackingmaterials/atomate/918/workflows/8652a6f8-4dcf-48fe-9260-2800349cd9fd/jobs/4018). Could you please take a look and fix it? Thanks!

**Comment by rkingsbury** [comment]
> Hi @rkingsbury It seems a value assertion error for the unit test of SCAN workflow [here](https://app.circleci.com/pipelines/github/hackingmaterials/atomate/918/workflows/8652a6f8-4dcf-48fe-9260-2800349cd9fd/jobs/4018). Could you please take a look and fix it? Thanks!

Hi @Zhuoying , I'm a bit confused by why this occurred, because it appears that the test file in the CI run you linked is not updated per this PR. Note that the value in the test changed from 0.34292 to 0.40503 in this merged PR, but somehow that change is not reflected in the stacktrace below. What branch / version is that CI run for? Is dependabot pulling in the latest atomate?

```
def test_SCAN_small_bandgap(self):
        # A structure with a small bandgap (LiH) should result in a KSPACING
        # value of 0.34292
    
        structure = Structure.from_file(
            os.path.join(reference_dir, "PBESol_pre_opt_for_SCAN_LiH/inputs", "POSCAR")
        )
    
        my_wf = get_wf(structure, "metagga_optimization.yaml")
        fw_ids = self._run_scan_relax(my_wf, "LiH")
    
        # Check PBESol INCAR
        ref_incar = Incar.from_file(
            os.path.join(reference_dir, "PBESol_pre_opt_for_SCAN_LiH/inputs", "INCAR")
        )
        incar = Incar.from_file(os.path.join(self._get_launch_dir()[0], "INCAR.gz"))
        for p in incar.keys():
            if p == "KSPACING":
                self.assertEqual(incar[p], 0.22)
            elif p == "ICHARG" or p == "ISTART":
                self.assertEqual(incar[p], 1)
            elif p == "METAGGA":
                self.assertEqual(incar[p], "None")
            elif p == "GGA":
                self.assertEqual(incar[p], "Ps")
            elif p == "EDIFFG":
                self.assertEqual(incar[p], -0.05)
            elif (
                p == "MAGMOM"
            ):  # Ignore MAGMOM b/c structure initialized from POSCAR cannot have a MAGMOM
                pass
            else:
                self.assertEqual(incar[p], ref_incar[p])
    
        # Check SCAN INCAR
        ref_incar = Incar.from_file(
            os.path.join(
                reference_dir, "SCAN_structure_optimization_LiH/inputs", "INCAR"
            )
        )
        incar = Incar.from_file(os.path.join(self._get_launch_dir()[1], "INCAR.gz"))
        for p in incar.keys():
            if p == "KSPACING":
>               self.assertAlmostEqual(incar[p], 0.34292, 4)
E               AssertionError: 0.405035627443234 != 0.34292 within 4 places (0.06211562744323401 difference)
```

**Comment by Zhuoying** [comment]
@rkingsbury Never mind. I thought this error was a py3test fail after your initial push but **before** I merged your PR into main.

**Pull request merged**
