### PR TITLE
Add eigenvalue_band_properties to VASP drone

### PR DESCRIPTION
**Pull request by mkhorton**
## Summary

An additive change, to help diagnose issues where band gap might be reported inconsistently from a Vasprun.

### CODE REVIEW

**Comment by utf** [comment]
Thanks @mkhorton 

Strange that tests are not running. Maybe CircleCI is down?

**Comment by utf** [comment]
Tests failed, are you able to fix @mkhorton?

**Comment by mkhorton** [comment]
Sure, I'll take a look, thanks for notification

**Comment by utf** [comment]
Tests still failing btw.

**Comment by mkhorton** [comment]
Working on it literally this second :-)

**Comment by utf** [comment]
Great thanks.

**Pull request merged**
