### PR TITLE
fix lobsterworkflow to work with add_additional_fields_to_taskdocs

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

Two small fixes so that the Lobster workflow works with "add_additional_fields_to_taskdocs".

### CODE REVIEW

**Comment by utf** [comment]
Thanks!

**Comment by JaGeo** [comment]
The failures in the py3devtest are weird. I will wait for the py3test. I might have to fix some problems.

**Comment by JaGeo** [comment]
Do you have any idea what is happening in the development tests?

**Comment by JaGeo** [comment]
Also, is there any plan to release a new atomate version? I would be very happy about it. I am currently working on a tutorial for the lobster workflow. :)

**Comment by utf** [comment]
Ok, the pymatgen dev tests should now be fixed. I've triggered them to run again.

As for a new atomate version, that is up to @computron

**Comment by utf** [comment]
The devtests are now failing due to some other changes that were made in pymatgen. I will fix those changes in a separate PR when I update the pymatgen version.

**Comment by JaGeo** [comment]
Thanks! And, as I said, I would be very happy about a new version :)

**Pull request merged**
