### PR TITLE
Ferroelectric workflow (2nd try)

### PR DESCRIPTION
**Pull request by blondegeek**
This pull requests adds the following classes and functions for the workflow for calculating the polarization of candidate ferroelectrics:
atomate.vasp.workflows.base.ferroelectric.get_wf_ferroelectric
atomate.vasp.fireworks.core.LcalcpolFW
atomate.vasp.fireworks.core.StaticInterpolateFW
(Some comments are included with suggestions for improving this FW)
atomate.vasp.firetasks.glue_tasks.GetInterpolatedPOSCAR
atomate.common.firetasks.glue_tasks.CreateFolder
atomate.common.firetasks.glue_tasks.GrabFilesFromCalcLoc
atomate.vasp.firetasks.parse_outputs.PolarizationToDbTask

Tests for get_wf_ferroelectric are included.

### CODE REVIEW

**Comment by computron** [comment]
Hi @blondegeek - thanks for trying this, but I'd like to review the number of files again. I'm going through all the atomate code and will make it to reviewing the tests code pretty soon - hopefully by end of this week. At that point I'll think harder about what can be done to minimize test files for some of the more complex workflows. Note also that some of the other tests that are already pulled into the repo also have too many files, so it's not the ferroelectric workflow in particular. I'll be going through those as well.

I'd also like to avoid putting VASP's POTCAR files, to the extent that it's reasonably possible, in the repo.

If I can't think of any changes then I'll merge as-is.

**Comment by computron** [comment]
Hi @blondegeek 

Bad news - I don't think I'll have time to solve this properly
Good news - I think we can just grandfather in your tests according to the previous policy like the others. Can you just:
1) gzip all your large files so that they take less space? Currently your test files are at 27MB. The previous biggest was 24MB for Raman (and more typically, a workflow is <10MB of test files).
2) start a fresh commit history so that we don't have the history of the previous files? e.g., do a fresh fork of atomate and apply your changes again from scratch?
3) ideally - move the test files to atomate/vasp/test_files and update unit tests as necessary (I recently refactored the tests so *all* the test files are there instead of scattered about)
4) submit a new PR?

Thanks!

**Comment by blondegeek** [comment]
Hi @computron. Gotcha. I will make the appropriate changes some time this week (just started at Google today so it will take me a little longer than normal to get to this).

**Comment by computron** [comment]
Hi @blondegeek 

Note that Alireza also pushed some changes about how to avoid output files by directly inserting a pre-generated task.json into the database instead of fake running VASP. I didn't look over the mechanics of this too carefully (e.g. code style) but it seems a viable way to reduce the number of files and reduce the tests. It's something to consider but optional for the PR - depending on your inclination.

**Comment by computron** [comment]
@blondegeek Any update on this PR? Hoping to get this in before the atomate paper submission so that the paper accurately reflects what's in atomate.

**Comment by blondegeek** [comment]
I'll be sure to do this before the submission.

**Pull request closed without merging**
