### PR TITLE
Documentation: installation guide

### PR DESCRIPTION
**Pull request by bocklund**
## Summary

Improved documentation. Open to feedback and suggestions.

### This commit:
* Improved installation tutorial (beginner)

### In progress:
* Custom YAML workflows (beginner)
* Custom Python workflows (from existing Fireworks) (intermediate)

### Future:
* Running workflows (from YAML library and Python) (beginner)
* Writing new Fireworks/Firetasks for workflows (machinery like envchk, powerups, passcalclocs) (advanced)
* Contributing - scope, separating concerns, code style guide, writing tests (intermediate)

If you have any feedback on my writing, organization of the docs, or planned documents (especially if you have ideas) please let me know.

### CODE REVIEW

**Comment by computron** [comment]
Thanks! I usually do code reviews on Fridays, I'll try to keep up to date with the latest documentation then

**Comment by computron** [comment]
@bocklund can you resolve the conflict above? Then I will just merge add additional comments

**Comment by bocklund** [comment]
Fixed

**Comment by computron** [comment]
Thanks!

**Pull request merged**
