### PR TITLE
Resubmit SCAN PR because I fail at Git

### PR DESCRIPTION
**Pull request by shyamd**
## Summary

I accidentally deleted my local/remote branch for the previous PR. Thankfully managed to save most of my changes and have made a new branch.

- Added in a new SCAN workflow
- Added in a powerup to clean up files after running
- updated the drone to store if the gap is indirect and the transitition
- moved some simple utils into atomate and removed pymatgen-db dependency
- fixed a bug in atwf powerup that prevented it from running
- fixed some misc bugs and codacy issues.

### CODE REVIEW

**Comment by computron** [comment]
Thanks! Can you see my comments from the previous PR?

**Comment by computron** [comment]
Since the previous comments aren't showing up for some reason, I've pasted them here:

screen shot 2018-01-12 at 2 16 15 pm

screen shot 2018-01-12 at 2 16 31 pm

**Comment by computron** [comment]
(let me know when finished making updates)

**Comment by shyamd** [comment]
This PR is done now.

**Comment by computron** [comment]
Thanks!

**Pull request merged**
