### PR TITLE
Require minimum maggma version 0.39.0

### LINKED ISSUE #728: M1 Mac incompatible
`atomate` cannot be installed on Apple Silicon due to a dependence on `pynng`:

```py
$ pip install atomate
Installing collected packages: pynng, pydash, orjson, msgpack, mongomock, mongogrant, jsonschema, joblib, importlib-metadata, gunicorn, flask-paginate, fastapi, dnspython, aioitertools, pymatgen-analysis-diffusion, maggma, FireWorks, custodian, atomate
    Running setup.py install for pynng ... error
ERROR: Command errored out with exit status 1:
     command: /Users/janosh/.venv/py310/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-zs7qj1q7/pynng_73e017c633ec429bbdd1f8be07cacbd5/setup.py'"'"'; __file__='"'"'/private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-zs7qj1q7/pynng_73e017c633ec429bbdd1f8be07cacbd5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-record-fcaj33sc/install-record.txt --single-version-externally-managed --compile --install-headers /Users/janosh/.venv/py310/include/site/python3.10/pynng
         cwd: /private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-zs7qj1q7/pynng_73e017c633ec429bbdd1f8be07cacbd5/
    Complete output (10 lines):
    /Users/janosh/.venv/py310/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      warnings.warn(
    WARNING: The wheel package is not available.
    running install
    /Users/janosh/.venv/py310/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    building mbedtls with: ['cmake', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-DENABLE_PROGRAMS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../prefix', '..']
    error: [Errno 2] No such file or directory: 'cmake'
```

Known issue tracked in https://github.com/codypiersall/pynng/issues/89. The dependence on `pynng` comes from [`maggma`](https://github.com/materialsproject/maggma) so perhaps issue can be solved there?

### PR DESCRIPTION
**Pull request by janosh**
Closes #728.

### CODE REVIEW

**Comment by munrojm** [comment]
Came here to open this PR, thanks @janosh.

**Comment by janosh** [comment]
Will try to update the code base for pymongo 4 compatibility tomorrow.

**Comment by janosh** [comment]
Ready for review.

**Comment by itsshawnzhang** [comment]
Thanks @janosh for your contribution! I merged this PR. 
Please let me know for any further problems or  concerns. Cheers:)

**Pull request merged**
