### PR TITLE
Absorption

### PR DESCRIPTION
**Pull request by yang-ruoxi**
## Summary

* Added AbsorptionFW to run a frequency-dependent dielectric calculation, with two options: independent-particle approximation (IPA) and random-phase approximation (RPA). One can also specify a static run, but it will invoke the MPStaticSet rather than the AbsorptionSet. 
* Added absorption task to write input sets for these runs 
* Added a section in vasp drones to collect the dielectrics information from RPA calculation, and to calculate the corresponding absorption coefficient for easy access. 
* A typical usage of this FW would be : 
 ```
 fw0 = OptimizeFW(structure)
 fw1 = AbsorptionFW(mode = "STATIC", parent = fw0) # uses MPStaticSet
 fw2 = AbsorptionFW(mode = "IPA", parent = fw1)   # uses AbsorptionSet supplied in pymatgen 
 fw3 = AbsorptionFW(mode = "RPA", parent = fw2)  # uses AbsorptionSet supplied in pymatgen 
 wf = Workflow([fw0, fw1, fw2, fw3])
```

### CODE REVIEW

**Comment by itsshawnzhang** [comment]
Hello @yang-ruoxi I think now you can run the workflows to test this PR. Please let me know for any problems or concerns.

Thanks for your contribution. Cheers! :)

**Comment by janosh** [comment]
Would be cool to get this merged!

@itsshawnzhang If @yang-ruoxi enabled edits by maintainers, you should be able to push a small change to this PR yourself and trigger CI that way.

**Comment by itsshawnzhang** [comment]
> Would be cool to get this merged!
> 
> @itsshawnzhang If @yang-ruoxi enabled edits by maintainers, you should be able to push a small change to this PR yourself and trigger CI that way.

Thanks @janosh and @yang-ruoxi. I will cerate a new PR from @yang-ruoxi 's adsorption branch and run the new CI at this point.

**Comment by janosh** [comment]
@itsshawnzhang Is allow edits from maintainers disabled? If so, it might be easier to add a the [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger to our `test.yml` GHA. I think that should allow you to trigger CI through a button and would avoid the need to create a duplicate PR.

workflow-dispatch-inputs

**Comment by itsshawnzhang** [comment]
> @itsshawnzhang Is allow edits from maintainers disabled? If so, it might be easier to add a the [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger to our `test.yml` GHA. I think that should allow you to trigger CI through a button and would avoid the need to create a duplicate PR.
> 
> workflow-dispatch-inputs

Will try this! Thanks!

**Comment by janosh** [comment]
@itsshawnzhang [This](https://github.community/t/support-to-run-workflow-dispatch-on-external-pr/186937/4) might be helpful.

> ```yml
> - uses: actions/checkout@v2
>   with:
>     ref: pull/${{ github.event.pull_request.id }}/head
> ```
> 
> If you want to manually dispatch a Workflow for a Pull Request you could use workflow_dispatch with an input of the Pull Request id that the Workflow then composes the ref from (in the format above).
>

**Comment by itsshawnzhang** [comment]
> 

This is helpful. Please allow me to look into it and I will create the check workflow for this PR. Thanks so much for the information @janosh :)

**Comment by yang-ruoxi** [comment]
> Thanks @janosh and @yang-ruoxi. I will push some changes to this PR and run the new CI at this point.

Thanks for looking into it! Is there anything I should do from my end to merge it?

**Comment by janosh** [comment]
@yang-ruoxi If you could push any change to this PR (fix a typo or improve a doc string or something like that) to retrigger CI that would allow @itsshawnzhang to make sure it passes all tests before merging.

**Comment by janosh** [comment]
@yang-ruoxi The failing tests are due to pymongo v3/v4 incompatibilities. Can you merge or rebase the `main` branch into your PR?

**Comment by itsshawnzhang** [comment]
Hello @yang-ruoxi . I merged this branch since all the tests are passed in the new environmental settings (see #744). Thank you so much for your contributions. Please let us know for any other problems or concerns. Cheers! : )

**Pull request merged**
