### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by janosh**
Follow up to #724.

### CODE REVIEW

**Comment by janosh** [comment]
@itsshawnzhang There are just 2 CI errors remaining now. I commented about one of them [over here](https://github.com/hackingmaterials/atomate/pull/399#issuecomment-1008646215). The other may be fixed by latest commit.

**Comment by itsshawnzhang** [comment]
Thank you for helping modifying all the changes in those files @janosh. I have reviewed all the changes and I think there will be less error in the circle CI after we merging this branch. Let's wait for the modification from #399 and go through the circle CI checking!

Please let us know for any further problems or concerns. Cheers! : )

**Comment by janosh** [comment]
Even after I pulled the latest changes from https://github.com/JaGeo/atomate/commit/09da51f65511d71952c35024e6c1a4bb2c3c2f3d, CircleCI was still complaining about the symlinks to Lobster files which caused the repo checkout to fail. So CircleCI didn't even get to running any tests.

Since
- I ran out of debugging ideas
- I'm more familiar with GitHub action
- was planning to submit a PR anyway to migrate away from CircleCI

I thought I might as well try it now and see if it too has trouble with the Lobster symlinks. The repo checks out fine now, even without the changes from https://github.com/JaGeo/atomate/commit/09da51f65511d71952c35024e6c1a4bb2c3c2f3d. Errors about the symlinks only start to appear later during `pytest`. Will try to pull the changes from https://github.com/JaGeo/atomate/commit/09da51f65511d71952c35024e6c1a4bb2c3c2f3d into here and improve the new [`.github/workflows/test.yml`](https://github.com/hackingmaterials/atomate/pull/730/commits/353cbf49ba32bce9961174ab92ae92ade9d959be) more later.

**Comment by itsshawnzhang** [comment]
My original thought was that the symlink directed to an empty file, which caused the circle CI <checkout code> error. But generally since @JaGeo update all the necessary files in #731 so I will merge that one firstly and we can move on from it. I appreciate very much for your help and contribution. Cheers! :)

**Comment by janosh** [comment]
@itsshawnzhang Sounds good. This PR might take a while anyway.. 😅

**Comment by itsshawnzhang** [comment]
> 

It's just so weird that the checkout code test stocked at symlink all the time....

**Comment by itsshawnzhang** [comment]
This line also need to be modified into <count_documents()>.
https://github.com/hackingmaterials/atomate/blob/31d359d9208a9b294a2dec0cb1ffc4f4fccde53d/atomate/vasp/firetasks/tests/test_lobster_tasks.py#L160

**Comment by itsshawnzhang** [comment]
Hello @janosh after adding the image from materialsvirtuallab, there is one more modification by @Zhuoying :
https://github.com/Zhuoying/atomate/blob/3495c5aba357fba0c7b4087b35ac84d025d92976/atomate/vasp/firetasks/tests/test_lobster_tasks.py#L161-L165.

If you correct these two errors, I think the code can run CI test without any problem.

**Comment by janosh** [comment]
> Hello @janosh after adding the image from materialsvirtuallab, there is one more modification by @Zhuoying : https://github.com/Zhuoying/atomate/blob/3495c5aba357fba0c7b4087b35ac84d025d92976/atomate/vasp/firetasks/tests/test_lobster_tasks.py#L161-L165.
> 
> If you correct these two errors, I think the code can run CI test without any problem.

Happy to try that. Though I specifically removed the `materialsvirtuallab` image because the `pymatgen` version installed was complaining about incompatible `python`.

**Comment by janosh** [comment]
Wow, you're right! No more errors. 🎉

**Comment by janosh** [comment]
Will remove the new GH workflow then and try to polish that in a separate PR so we can finally merge a working CircleCI into `main`.

**Comment by Zhuoying** [comment]
Hi @janosh Thank you for your helpful contribution to fixing the CI issue. @itsshawnzhang and I found that `python` incompatibility issue with `pymatgen` is due to NumPy update. The latest `NumPy` (1.22.0) has a big release that drops the support of python3.7. So the latest `pymatgen`(2022.01.09) requires `python>=3.8`. Here in the requirements.txt, we set `pymatgen=2022.0.10`(still use `Numpy=1.21.3` and `python3.7`), so it should not be an issue for now. There will be a big to-do-list when we update to `NumPy1.22.0` and `python3.8` later.

**Comment by janosh** [comment]
@Zhuoying I see. Thanks a lot for your help! 👍 

I cleaned up the commit history a bit and removed the GH action workflow. Hopefully all green after last commit.

**Comment by Zhuoying** [comment]
I think the `py3devtest` error is caused by this line `pip install git+https://github.com/materialsproject/pymatgen.git --upgrade` in .circleci/config.yaml. It will upgrade `pymatgen=2020.1.9`(requires `python>=3.8`). 
We appreciate your tidy manner of coding. After it turns green, we will merge this PR.

**Comment by janosh** [comment]
Yeah, forgot about that line. Just removed and re-pushed the last commit.

**Comment by Zhuoying** [comment]
@janosh Wow, it finally turns green for all tests. 
I noticed that NumPy1.22.0 also caused some troubles in pymatgen latest version. So we will wait for a steady pmg version that is compatible with NumPy1.22.0 and python3.8 and then upgrade our requirements for pmg.
Thanks again for your contributions!

**Pull request merged**
