### PR TITLE
Ferroelectric workflow

### PR DESCRIPTION
**Pull request by blondegeek**
This pull requests adds the following classes and functions for the workflow for calculating the polarization of candidate ferroelectrics:
atomate.vasp.workflows.base.ferroelectric.get_wf_ferroelectric
atomate.vasp.fireworks.core.LcalcpolFW
atomate.vasp.fireworks.core.StaticInterpolateFW
     (Some comments are included with suggestions for improving this FW)
atomate.vasp.firetasks.glue_tasks.GetInterpolatedPOSCAR
atomate.common.firetasks.glue_tasks.CreateFolder
atomate.common.firetasks.glue_tasks.GrabFilesFromCalcLoc
atomate.vasp.firetasks.parse_outputs.PolarizationToDbTask

Tests for get_wf_ferroelectric are included.

### CODE REVIEW

**Comment by computron** [comment]
Hi @blondegeek - I appreciate the attention to detail having test files but can we bring the file count to < 293 files changed? e.g., by an order of magnitude. For all the various interpolations you may want to only test (i) a few interpolations, e.g. one of each type and (ii) only small portions of the input/output. Otherwise we are going to end up with a million files in atomate and cloning the repo is going to take forever.

See the announcement here:
https://groups.google.com/forum/#!topic/atomate/l9XWPIEftz4

**Comment by bocklund** [comment]
It also seems like with some of the images code should have overlap with the NEB code. We should try to pick the better solution and use it in both places, if possible

**Comment by blondegeek** [comment]
Hi @computron, I've reduced the number of files by ~1/3. I'm not sure how to reduce if further. The test now only uses one interpolation and uses a bson file to load data into task db (1 mb of data) that then get's used to test PolarizationToDbTask. The test directory for the ferroelectric workflow is still 27 mb -- due to still having 8 OUTCAR's and vasprun.xml's. Any recommendations for how to trim the OUTCAR and vasprun files down?

**Comment by bocklund** [comment]
You have to rebase the removed files out of the commit history, otherwise they are still going to be carried around in the git history and you'll still have to download them when you clone.

**Comment by computron** [comment]
Or I imagine you can just create a new branch with the changes you want (when finished) and I can just merge those

**Comment by blondegeek** [comment]
@computron I'm closing this pull request and making one for the new branch.

**Comment by blondegeek** [comment]
@computron Also, what's the most kosher thing to do with these extra commits on my master branch? Ideally, I want my master branch sync'd with atomate master. Should I do a hard reset once the other pull request has been merged?

**Comment by computron** [comment]
@blondegeek not completely sure. There is the rebase option that Brandon mentioned, but I never took the time to wrap my head around that (and if you attempted it, I would very much suggest you copy your codebase to some temporary directory first). For now I guess my concentration is on figuring out how to solve the "number of test files in atomate tests" problem, and I'll think more about this specific situation after going through the code review.

**Pull request closed without merging**
