### PR TITLE
use pytest-split in GHA test workflow

### PR DESCRIPTION
**Pull request by janosh**
Following the initially longer than expected runtime of `pytest` in #734, I looked around a bit for a pytest plugin that would automatically distribute the workload among multiple concurrent runners.

Luckily, exactly such a thing exists. Never used it before but looks great.

https://github.com/jerry-git/pytest-split

And they even have a GHA demo:

https://github.com/jerry-git/pytest-split-gh-actions-demo/tree/master/.github/workflows

Let's see if I set this up correctly. :)

### CODE REVIEW

**Comment by itsshawnzhang** [comment]
Hello @janosh! Sorry about the delay. I will merge this PR now and please let me know for any other problems or concerns.
Thank you for the contribution. Cheers! :)

**Comment by janosh** [comment]
Tbh, I'm not sure the potential CI speed up from this change is worth the added complexity. I guess we can try it out on `main` and revert if it causes any issues.

**Comment by itsshawnzhang** [comment]
@janosh Sure thing!

**Comment by itsshawnzhang** [comment]
@janosh I think I need to revert this PR since several errors arose by the `get_valid_path` in `drone.py` from `qchem` package.

**Comment by janosh** [comment]
Feel free.

**Pull request merged**
