### PR TITLE
Q-Chem 6 + Misc Updates

### PR DESCRIPTION
**Pull request by samblau**
## Summary

* A variety of additions and modifications for Q-Chem 6, including supporting new Q-Chem features and updating Pymatgen and Custodian functionality and default values. 
* Parsing raw gradient and Hessian files. Hessians are particularly important, because they are not printed in the output file, and saving them allows us to then print them out and use them as inputs to a subsequent optimization calculation.
* Some minor additions related to dipoles and HOMO/LUMO gap info.

### CODE REVIEW

**Comment by samblau** [comment]
@Zhuoying, what's up with all the failing VASP tests? I haven't changed any VASP code. Might be due to switching to a newer pymatgen version? Your help would be appreciated.

**Comment by samblau** [comment]
@naik-aakash Seems like lobster tests are failing here too

**Comment by JaGeo** [comment]
Some keys in the lobsterout class changed. We will fix it. Shouldn't take too long.

**Comment by naik-aakash** [comment]
> @naik-aakash Seems like lobster tests are failing here too

@samblau , I will fix it tomorrow morning. Thanks for notifying. :-)

**Comment by naik-aakash** [comment]
#771 This PR will fix failing lobster tests @samblau.

**Comment by Zhuoying** [comment]
Hi @samblau , thanks for the PR. I just merged the PR by @naik-aakash on lobster test fix. 
You could git pull first. I saw a failure in `atomate/qchem/tests/test_drones.py` may need a fix before passing the tests. If all tests pass, I will merge this PR. Thanks!

**Comment by samblau** [comment]
@Zhuoying We're good to go

**Comment by Zhuoying** [comment]
@samblau Great! Thanks for the excellent contribution. I just merged it~

**Pull request merged**
