### PR TITLE
PassResult refactor of PassXY fireworks

### PR DESCRIPTION
**Pull request by montoyjh**
## Summary

This PR generalizes the PassX property passing fireworks used in workflows that need to pass selected data from individual fireworks to other fireworks e. g. Elastic, Raman tasks.

* PassResult is added to atomate.common.firetasks.glue_tasks.  Takes a `pass_dict` keyword that allows for the retrieval of an attribute or mongo-style dictionary entry (e. g. `>>ionic_steps.-1.stress`) by from a given pymatgen output file class initiated using the `parse_class` and `parse_kwargs` parameters.  Can also take a mod_spec_cmd (e. g. `_push`, `_set`, and a mod_spec_key to indicate where to place the result in the child firework specs.
* adds atomate.vasp.firetasks.glue_tasks.pass_vasp_result helper function that simplifies the above procedure for getting and passing data from a vasp run (e. g. one derived from Vasprun's parsing of vasprun.xml.gz)
* Updated elastic workflow to use this functionality as opposed to PassStressStrain
* Updated raman workflow to use this functionality as opposed to PassEpsilon and PassNormalmodes

### CODE REVIEW

**Comment by computron** [comment]
@montoyjh can you confirm that

i) recursive_get_result is not essentially the same thing as "get_mongolike" already in atomate utils? (except using >> instead of dot notation)
ii) if there really are very clear and separate use cases, move recursive_get_result into utils

**Comment by computron** [comment]
@montoyjh Also I pulled your elastic PR before this one so there is also a merge conflict to resolve

**Comment by montoyjh** [comment]
recursive get result is slightly different, in that it walks through the dictionary and converts any relevant keys using a reference dictionary, but does duplicate get_mongolike's functionality partially (in the conversion of dot notation for dictionary key accessing).  I've removed that duplication in the function and moved it to utils.

**Comment by computron** [comment]
Thanks! Can you also add independent unit tests for recursive_results? Also include examples in the docstring. This will help people understand how to use this notation

**Comment by montoyjh** [comment]
Agreed.  Will add later this week.

**Comment by computron** [comment]
Thanks!

**Pull request merged**
