### PR TITLE
Qchem update

### PR DESCRIPTION
**Pull request by espottesmith**
NOTE: This should not be merged in until Custodian PR #165 is merged and a new Custodian version is released.

## Summary

This PR adds additional functionality to the qchem module:
* PerturbGeometry, a FireTask to modify the atoms in a molecule by some vector (for instance, a vibrational frequency mode)
* TransitionStateFW, a Firework for transition-state geometry optimization
* PESScanFW, a Firework for potential energy surface scans
* FrequencyFlatteningTransitionStateFW, a Firework for repeated frequency -> ts-opt calculations (to ensure convergence to a first-order saddle point)
* get_wf_reaction_path_with_ts, which returns a Workflow that resembles an intrinsic reaction coordinate (IRC) calculation; perturbs a transition-state in each direction along an imaginary frequency mode and optimizes to determine which minima are linked by the TS.

### CODE REVIEW

**Comment by utf** [comment]
Can you let me know if this is ready to merge?

**Comment by espottesmith** [comment]
I realized when I received this message that I had forgotten to add one feature to this PR (the QChemDrone class wasn't equipped to parse TS calculations). I just added that in the last two commits.

Assuming those pass all tests, this should be ready to merge. However, you might want to wait until custodian releases a new version, as this does rely on the most recent changes to that repo.

**Comment by samblau** [comment]
I believe the Custodian PR has been merged and a new version released...? Is this good to go @espottesmith?

**Comment by espottesmith** [comment]
The latest custodian version is 2021.02.08, which I don't think includes my changes.

**Comment by samblau** [comment]
That's annoying. You might need to ping Shyue to get him to release a new version

**Comment by espottesmith** [comment]
@shyuep, can you provide some insight as to when the next version of custodian will be released? We'll need a new version in order for this PR to be merged into atomate.

**Comment by itsshawnzhang** [comment]
Hello @espottesmith, I am here to follow up on this. The custodian now has a version of 2021.12.2. Could you please let me know for any update from this PR? Thanks so much for your contribution. Cheers!

**Comment by espottesmith** [comment]
It's been nearly a year since I looked at some of this code, so it might take me a while to get all tests to pass and make sure everything is as it should be. But with a new version of custodian including my previous changes, there should be no other impediment outside of myself to merging in this PR.

**Comment by espottesmith** [comment]
Looks like at least one of the testing workflows is having trouble installing openbabel; I'm not sure if I'm allowed to change those workflows (I suspect not). If not, then I suggest installing openbabel with conda, rather than with apt and pip. Conda seems to be the most stable way to install it, in general.

**Comment by espottesmith** [comment]
Other than the issue with OpenBabel, tests pass, and this should be ready to merge.

**Comment by samblau** [comment]
I can work on fixing the GitHub OpenBabel issue on my PR, which I assume is next in line for revival after this one is merged

**Comment by itsshawnzhang** [comment]
Hello @espottesmith. Thank you so much for your contributions. I think the circleCI tests are passed. We are still working on the Github test for now. I will now review and merge this PR. Besides, @samblau I appreciate your help in fixing Github OpenBabel as well!

Please contact/pin/at me anytime for any problems or concerns. Cheers! : )

**Comment by janosh** [comment]
@espottesmith Sorry, the GH action with failing `openbabel` install is my fault. I accidentally included it in #730 even though the workflow wasn't finished nor error-free yet. Will be fixed in #734 -- hopefully soon.

**Pull request merged**
