### PR TITLE
add new custodian handlers for VASP workflows; separate SCAN and R2SCAN wflows

### PR DESCRIPTION
**Pull request by rkingsbury**
## Summary

* Add `LargeSigmaHandler` to all VASP workflows by default
* Add `IncorrectSmearingHandler` to all VASP workflows by default
* Add `ScanMetalHandler` to all SCAN calculations
* Add a separate `wf_scan_opt` and `wf_r2scan_opt` to make it easy for users to run either SCAN or R2SCAN optimizations using the same workflow structure

### CODE REVIEW

**Comment by rkingsbury** [comment]
Pulled the latest master here as well; hopefully this fixes the tests

**Comment by rkingsbury** [comment]
@utf do you know if the CI tests are pegged to a specific version of custodian? This PR requires some new handlers that were incorporated into the latest custodian release (as of a few hours ago), but CircleCI is still throwing import errors. Can you let me know if I need to do anything else to get the tests working? Thanks.

**Comment by utf** [comment]
Yes, the custodian version is set here: https://github.com/hackingmaterials/atomate/blob/fd5655d5779d429c0c2387df5336d0135693d9a3/requirements.txt#L12

You can update that file to point to the latest version.

**Comment by rkingsbury** [comment]
The only tests failing now are 4 QChem related tests. @samblau did I see a comment from you recently related to why the atomate tests for Qchem are broken right now? I'm fairly certain this isn't caused by anything in my PR (unless the new custodian handlers for Qchem have changed the output of certain tests)

**Comment by utf** [comment]
It looks like @samblau's QChem PR (#560) is passing the tests. Once that's merged I will ask you to pull those changes into this branch and hopefully fix these failing tests too.

**Comment by samblau** [comment]
@rkingsbury @utf It is partly due to my PR that was merged into Custodian yesterday, hence why I was already working on this. I should be just minutes away from my PR being good to go.

**Comment by utf** [comment]
@rkingsbury I've just merged the QChem PR. Could you please pull the latest changes from master into this branch.

**Comment by utf** [comment]
Thanks @rkingsbury!

**Pull request merged**
