### PR TITLE
Add additional optimization to Lobster

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

This is WIP. I would like to add an optimization to the Lobster workflows. Some more tests need to be added.

### CODE REVIEW

**Comment by JaGeo** [comment]
Hi, 

I am still very much interested in getting this request merged.

Thank you very much.

**Comment by mkhorton** [comment]
Hi @JaGeo,

@Zhuoying and @itsshawnzhang from @computron's group have taken over routine maintenance of this repository, due in part because of how long PRs have been open. I'm not sure if there's been a public announcement of this.

@Zhuoying or @itsshawnzhang, would it be possible to review and merge this PR if you're satisfied with it? @JaGeo is a long time contributor to atomate.

**Comment by Zhuoying** [comment]
Sure, thanks for the reminder @mkhorton.
Hi @JaGeo, we are dealing with the cumulated PRs, will review it and merge your PRs soon. Thank you for your contribution!

**Comment by itsshawnzhang** [comment]
We have merged this PR. Please let us know for any problems or concerns.

**Comment by JaGeo** [comment]
Thank you all 🙂

**Pull request merged**
