### PR TITLE
Fix for test file issue in Lobster workflows

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

I hope to fix the test files issues for the Lobster workflows.

### CODE REVIEW

**Comment by JaGeo** [comment]
Just wanted to add that locally all lobster tests are passing. I was just able to confirm again.

**Comment by itsshawnzhang** [comment]
> 

It seems to me that there is no circle CI testing for this lobster tests. I am not sure if it's blocked by the symlink issue or by something else. But I will just make sure that we have all the necessary files to pass the checkout code (symlink) session for #730.

**Comment by JaGeo** [comment]
I see. Thanks.

**Comment by itsshawnzhang** [comment]
> I see. Thanks.

No problem! Thanks so much for your contribution and help! Will let you know if there is any problems. Cheers! :)

**Comment by itsshawnzhang** [comment]
Hello @JaGeo, when I tried to run circleCI testing, the system returned me such error:
https://app.circleci.com/pipelines/github/itsshawnzhang/atomate/7/workflows/ec68e65f-234c-41bf-9f30-93d4a0d75690/jobs/10?invite=true#step-103-489

Do you have any idea where did it came from? I tried replace <count()> but somehow the <gridfs> is a cursor type and has no attribute of <count()>.

Thanks so much for your help. Cheers! :)

**Comment by JaGeo** [comment]
I will try look into it today. 
Nothing like this happened when testing these tests on my local computer with a MongoDB database. Will check again.

**Comment by itsshawnzhang** [comment]
> I will try look into it today. Nothing like this happened when testing these tests on my local computer with a MongoDB database. Will check again.

sorry I deleted that previous message. We fixed it by using <list()> rather than <count()>. 
https://github.com/hackingmaterials/atomate/pull/730#issuecomment-1010603960

Please let me know if those are acceptable, or there is any other problems or concerns. Cheers! :)

**Comment by JaGeo** [comment]
Okay, great. Will test it again this morning. 🙂

**Pull request merged**
