### PR TITLE
[WIP][test]update test.yml to check PR 726

### PR DESCRIPTION
**Pull request by itsshawnzhang**
update test.yml with manual workflow_dispatch to import #726 for CI testing.

### CODE REVIEW

**Comment by itsshawnzhang** [comment]
Hello @janosh. Do you think this would work? I can just close the PR once it passes the test. But when I tried to include the ref of PR 726, it gave the error:

</usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/pull/726/head*:refs/remotes/origin/pull/726/head* +refs/tags/pull/726/head*:refs/tags/pull/726/head*
The process '/usr/bin/git' failed with exit code 1
Waiting 19 seconds before trying again
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/pull/726/head*:refs/remotes/origin/pull/726/head* +refs/tags/pull/726/head*:refs/tags/pull/726/head*
Error: The process '/usr/bin/git' failed with exit code 1>

Do you have any idea about such error?

Thanks so much for your help! Cheers!

**Comment by janosh** [comment]
I was thinking more along the lines of

```yml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # new
  workflow_dispatch:
      pr:
        description: Pull request against which to trigger CI. Must be 'pull/:id/head' with id replaced by the PRs number.
        type: string
        default: ''

- uses: actions/checkout@v2
  # new
  with:
    ref: pull/${{ github.event.pull_request.id }}/head
```

never tried this though so don't know if it works as intended. Also, @yang-ruoxi replied on #726 so perhaps we just wait for him to push there.

**Comment by itsshawnzhang** [comment]
> I was thinking more along the lines of
> 
> 
> 
> ```yml
> 
> on:
> 
>   push:
> 
>     branches: [main]
> 
>   pull_request:
> 
>     branches: [main]
> 
>   # new
> 
>   workflow_dispatch:
> 
>       pull_request:
> 
>         description: Pull request against which to trigger CI. Must be 'pull/:id/head' with id replaced by the PRs number.
> 
>         type: string
> 
>         default: ''
> 
> 
> 
> - uses: actions/checkout@v2
> 
>   # new
> 
>   with:
> 
>     ref: ${{ github.event.inputs.pull_request }}
> 
> ```
> 
> 
> 
> never tried this though so don't know if it works as intended. Also, @yang-ruoxi replied on #726 so perhaps we just wait for him to push there.

Thanks @janosh for your help! A more straightforward way I can help to ruoxi is to just copy paste all her changed files into this PR, so that we are running the test using the new environment. If the test passes, I can close this PR and merge hers into the main branch.

**Comment by janosh** [comment]
Or you could check out her PR locally by adding her fork as a local `remote`, merge `main` into it and push back. As a maintainer, you have push access to her branch by default.

**Comment by itsshawnzhang** [comment]
> 

I see. It looks easier in that way! Thanks @janosh !

**Comment by itsshawnzhang** [comment]
> Or you could check out her PR locally by adding her fork as a local `remote`, merge `main` into it and push back. As a maintainer, you have push access to her branch by default.

All the tests are passed from my side. I think it's good to go to merge #726. Thanks very much for your help @janosh! ; )

**Pull request closed without merging**
